[workspace]
authors = ["Pierre Guillou <pierre.guillou@minesparis.psl.eu>"]
channels = ["conda-forge"]
description = "Simple Morphological Image Library"
name = "smil"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
cmake = ">=4.0.2,<5"
cxx-compiler = ">=1.9.0,<2"
swig = ">=4.3.1,<5"
libpng = ">=1.6.47,<2"
libtiff = ">=4.7.0,<5"
libjpeg-turbo = ">=3.1.0,<4"
libcurl = ">=8.14.0,<9"
zlib = ">=1.3.1,<2"
qwt = ">=6.3.0,<7"
