name: publish_manylinux
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
  workflow_dispatch:

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/${{ matrix.image }}
    strategy:
      matrix:
        python: [
          "cp39-cp39",
          "cp310-cp310",
          "cp311-cp311",
          "cp312-cp312",
          "cp313-cp313"
          ]
        image: [
           manylinux_2_28_x86_64
        ]

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y \
            sudo \
            libcurl-devel \
            libjpeg-devel \
            libtiff-devel \
            freetype-devel

      - name: Register the python version
        run: |
          echo "/opt/python/${{ matrix.python }}/bin" >> $GITHUB_PATH

      - name: Install python dependencies
        run: |
          pip install swig numpy build ninja

      - name: Checkout libpng
        uses: actions/checkout@v5
        with:
          repository: "pnggroup/libpng"
          ref: "v1.6.50"
          path: "libpng"

      - name: Build static libpng
        run: |
          cd libpng
          mkdir build
          cd build
          cmake \
            -DCMAKE_INSTALL_PREFIX=$PWD/install \
            -DPNG_SHARED=OFF \
            -DPNG_EXECUTABLES=OFF \
            ..
          echo CMAKE_PREFIX_PATH=$PWD/install/lib/cmake:$CMAKE_PREFIX_PATH >> $GITHUB_ENV

      - name: Create & configure Smil build directory
        run: |
          mkdir build && cd build
          cmake \
            -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
            -DBUILD_TEST=ON \
            -DWRAP_PYTHON=ON \
            $GITHUB_WORKSPACE
        env:
          CMAKE_GENERATOR: "Ninja"
          CMAKE_BUILD_TYPE: Release

      - name: Build Smil
        run: |
          cmake --build build --config Release

      - name: Build Python package
        run: |
          cmake --build build --config Release --target python_package

      - name: Build wheel from Python package
        run: |
          cd build/python
          python -m build --wheel -C="--build-option=--plat-name=${{ matrix.image }}"
          cd ../..
          echo "MY_PKG=$(ls build/python/dist/*)" >> "$GITHUB_ENV"

      - uses: actions/upload-artifact@v4
        with:
          name: linux-python-package-x64-${{ matrix.py }}
          path: ${{ env.MY_PKG }}

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: quay.io/pypa/${{ matrix.image }}
    strategy:
      matrix:
        python: [
          "cp39-cp39",
          "cp310-cp310",
          "cp311-cp311",
          "cp312-cp312",
          "cp313-cp313"
          ]
        image: [
           manylinux_2_28_x86_64
        ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: linux-python-package-x64-${{ matrix.py }}

      - name: Register the python version
        run: |
          echo "/opt/python/${{ matrix.python }}/bin" >> $GITHUB_PATH

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.py }}
          activate-environment: true

      - name: Install Python package
        run: |
          uv pip install "$(ls *.whl)"

      - name: Test Python import
        run: |
          python -c 'import smilPython as sp; dir(sp)'

      - name: Test Python scripts
        run: |
          Copy-Item -Path "images\*" -Destination "doc\demos\python" -Recurse
          cd doc/demos/python/
          python base_graph.py
          python benchs.py
          python blob_measures.py
          python constrained_watershed.py
          python copy_crop.py
          python example-3D-image-rotate.py
          python example-areathreshold.py
          python example-asfclose.py
          python example-bresenham.py
          python example-default-se.py
          python example-distance-geodesic.py
          python example-gaussian-filter.py
          python example-horiz-convolve.py
          python example-imagefileinfo-print.py
          python example-inertia-matrix.py
          python example-intro-blobs.py
          python example-point-minus.py
          python example-read.py
          python example-readRAW.py
          python extinction_values.py
          python first-program.py
          python hit_or_miss.py
          python loop-input.py
          python loop-sleep.py
          python multichannel_operations.py
          python numpy_array.py
          python numpy_np2image.py
          python numpy_np2sp.py
          python numpy_sp2np2sp.py
          python numpy_sp2np.py
          python operators.py
          python skiz.py
          python thresholds.py
          python x_image_01.py
